export const ADD_SURVEY = 'ADD_SURVEY';
export const EDIT_SURVEY = 'EDIT_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const MOVE_SURVEY = 'MOVE_SURVEY';
export const ADD_TAB = 'ADD_TAB';
export const DELETE_TAB = 'DELETE_TAB';
export const FOCUS_TAB = 'FOCUS_TAB';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_VALUE = 'SET_VALUE'; //TODO -- set values in reducers
